[[build]]
  base = "apps/codebase"
  command = "pnpm turbo run build --filter=codebase"
  publish = "apps/codebase/dist"

[[build]]
  base = "apps/next-app"
  command = "pnpm turbo run build --filter=next-app"
  publish = "apps/next-app/.next"
