[[build]]
  base = "/frontend"
  command = "pnpm turbo run build --filter=frontend"
  publish = "frontend/dist"

[[build]]
  base = "/next"
  command = "pnpm turbo run build --filter=next"
  publish = "next/.next"
